-- 테이블 생성 QUERY
CREATE TABLE SCHEDULE (
	ID INT(10) NOT NULL AUTO_INCREMENT,
	PASSWD VARCHAR(4) NOT NULL,
	TITLE VARCHAR(20) NOT NULL,
	MEMO VARCHAR(200),
	USERID VARCHAR(10) NOT NULL <- FK,
	REGTIME DATE NOT NULL,
	EDITTIME DATE,
	CONSTRAINT SCHEDULE_PK PRIMARY KRY(ID),
	CONSTRAINT SCHEDULE_FK FOREIGN KEY(USERID) REFERENCES USER(ID)
);
	
CREATE TABLE USER (
	ID INT(10) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	REGTIME DATE NOT NULL,
	EDITTIME DATE,
	CONSTRAINT USER_PK PRIMARY KRY(ID)
);

-- 일정 생성 QUERY
INSERT INTO SCHEDULE (PASSWD, TITLE, MEMO, USERID, REGTIME, EDITTIME)
	       VALUE (:PASSWD, :TITLE, :MEMO, :USERID, SYSDATE(), SYSDATE())


-- 전체 일정 조회 QUERY
SELECT ID, PASSWD, TITLE, MEMO, USERID, REGTIME, EDITTIME
  FROM SCHEDULE
 WHERE DATE(EDITTIME) = :EDITTIME
   AND USERID = :USERID
 ORDER BY EDITTIME DESC


-- 선택 일정 조회 QUERY
SELECT ID, PASSWD, TITLE, MEMO, USERID, REGTIME, EDITTIME
  FROM SCHEDULE
 WHERE ID = :ID


-- 선택 일정 수정 QUERY
UPDATE SCHEDULE
   SET TITLE = :TITLE,
       MEMO = :MEMO,
       USERID = :USERID
       EDITTIME = SYSDATE()
 WHERE USERID = :


-- 선택 일정 삭제 QUERY
DELETE SCHEDULE
 WHERE ID = :ID
